general {
    base_exp_dir = ./exp/CASE_NAME
    recording = [
        ./,
    ]
}

run_network {
    input_resolution = [512, 512]
    rgb_threshold = 0.1
}

dataset {
    data_dir = ./data/CASE_NAME/
    render_cameras_name = cameras_sphere.npz
    object_cameras_name = object_sphere.npz
}
